name: Rust Build
description: Setups a Rust project for AWS Lambda

runs:
  using: "composite"
  steps:
    - uses: dtolnay/rust-toolchain@stable

    - uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.13.0

    # Install Cargo Lambda from source until 1.5 is released
    #
    # - uses: cargo-bins/cargo-binstall@main
    # - name: Install cargo-lambda
    #   shell: bash
    #   run: cargo binstall -y cargo-lambda
    #
    - name: Install cargo-lambda
      shell: bash
      run: |
        git clone https://github.com/cargo-lambda/cargo-lambda.git && \
        cd cargo-lambda && \
        make install-local

    - uses: Swatinem/rust-cache@v2